AWSTemplateFormatVersion: '2010-09-09'

Resources:
  ecstaskstate: # Used to capture ECS Task State
    Type: AWS::Serverless::SimpleTable
    Properties:
      PrimaryKey:
        Name: id
        Type: String
      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5
    
Outputs:
  TableName:
    Value: !Ref 'ecstaskstate'
    Description: Table name of the newly created DynamoDB table
