AWSTemplateFormatVersion: '2010-09-09'


Resources:
  ecsctrinstancestate: # Captures ECS Container Instance state
    Type: "AWS::DynamoDB::Table"
    Properties:
      PrimaryKey:
        Name: id
        Type: String
      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5
    
Outputs:
  TableName:
    Value: !Ref 'ecsctrinstancestate'
    Description: Table name of the newly created DynamoDB table
